In [2]:
import cv2
import numpy as np

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


Load Data

In [4]:
inputs = np.load("/content/drive/MyDrive/EECS545 Final Project/CorrectData/test_input.npy")
labels = np.load("/content/drive/MyDrive/EECS545 Final Project/CorrectData/test_labels.npy")

print(inputs.shape)
print(labels.shape)

(1659, 3, 310, 360)
(1659, 3, 310, 360)


In [4]:
print(inputs[0, 1, :, :])

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [6]:
for i in range(0,inputs.shape[0]):
  imgFile = "/content/drive/MyDrive/EECS545 Final Project/CorrectData/Training Images/Inputs/Test_img_{index}.tif".format(index = i)
  labelFile = "/content/drive/MyDrive/EECS545 Final Project/CorrectData/Training Images/Labels/Test_label_{index}.tif".format(index = i)
  img = cv2.imwrite(imgFile, inputs[i, 1, :, :]*255)
  lbl = cv2.imwrite(labelFile, labels[i, 1, :, :]*255)